it('guardando_datos', function () {
    cy.visit('https://5r1t37dq-4200.brs.devtunnels.ms/pacientes');
    cy.get('.tunnel--dwithport-text22 > span').click();
    cy.get('#mat-input-0').clear('b');
    cy.get('#mat-input-0').type('brad');
    cy.get('.mdc-button__label').click();
    cy.get('[data-index="13"] > .center').click();
    cy.get(':nth-child(1) > .ml-2').click();
    cy.get('.body > :nth-child(2)').click();
    cy.get(':nth-child(2) > .ml-2').click();
    cy.get('.inset-0').click();
    cy.get('[data-index="45"] > .top').click({ force: true });
    cy.get(':nth-child(1) > .ml-2').click();
    cy.get('.body > :nth-child(1)').click();
    cy.get(':nth-child(2) > .ml-2').click();
    cy.get('.inset-0').click();
    cy.get('.row-with-border > .tooth-with-margin-left > .bottom').click();
    cy.get(':nth-child(2) > .ml-2').click();
    cy.get('.body > :nth-child(2)').click();
    cy.get('.body > :nth-child(3)').click();
    cy.get('.inset-0').click();
    cy.get('[data-index="42"] > .center').click();
    cy.get('.body > :nth-child(2)').click();
    cy.get('.body > :nth-child(2)').click();
    cy.get('.body > :nth-child(3)').click();
    cy.get('.inset-0').click();
    cy.get(':nth-child(2) > .tooth-with-margin-left > .center').click({ force: true });
    cy.get(':nth-child(2) > .ml-2').click();
    cy.get('.body > :nth-child(2)').click();
    cy.get(':nth-child(2) > .ml-2').click();
    cy.get('.inset-0').click();
    cy.get('[data-index="12"] > .bottom').click();
    cy.get(':nth-child(2) > .ml-2').click();
    cy.get('.body > :nth-child(1)').click();
    cy.get(':nth-child(2) > .ml-2').click();
    cy.get('.body > :nth-child(1)').click();
    cy.get('.inset-0').click();
    cy.get('[data-index="43"] > .center').click({ force: true });
    cy.get('.body > :nth-child(2)').click();
    cy.get('.selected-treatments').click();
    cy.get(':nth-child(1) > .ml-2').click();
    cy.get(':nth-child(2) > .ml-2').click();
    cy.get('.body > :nth-child(1)').click();
    cy.get('.inset-0').click({ force: true });
    cy.get('#especificaciones')
        .type('Especificaciones de prueba para el paciente');
    cy.get('#observaciones')
        .type('Observaciones de prueba para el paciente');
    cy.contains('button', ' Guardar Odontograma ').click({ force: true });
    cy.contains('button', ' Aceptar ').click({ force: true });
});
